### ISSUE TITLE
One Sytem, Five Languages (Somali, Xhosa, Pashto, Twi, Ukrainian)

### ISSUE THREAD

**Issue by xiao11lam** [linguisticsjusticeleague/PuzzLing-and-Scoring#1]
Hey, guys! Hope everyone had a good day!
I think here is a issue we need to fix with is that we need to **have five languages supported on our Puzzling system.** This can be a front-end challenge as well as the backend. Especially we need firstly design with a more user friendly front-end, and then consider about the back-end compatibilities at the same time.

**Comment by xiao11lam** [comment]
![Screenshot from 2022-06-25 23-59-31](https://user-images.githubusercontent.com/58770171/175803288-2ac1f87f-1d8e-4f09-a6c0-cf412378bb7e.png)
Here are the front-end I am thinking, there has a "chooser" before the header, so users can choose their language, already pushed in the code, please check there.

**Comment by yanbo8204** [comment]
Hi folks, I think now the language selection feature is implemented. Let me know what you guys think of it.

**Comment by xiao11lam** [comment]
Thank you @kz209 I am already testing it, thank you for your contributions!

**Comment by yanbo8204** [comment]
Thanks, @xiao11lam. If everything is all right, I will close this issue to mark it as solved, but feel free to reopen it if having any other questions.
