### ISSUE TITLE
The result page refresh issue ```home/routes.py``` that cause the semantics scoring method inconsistency. 

### ISSUE THREAD

**Issue by xiao11lam** [linguisticsjusticeleague/PuzzLing-and-Scoring#3]
Hey, there, here are the issues:
When I did the user input from the user texting box.
![image](https://user-images.githubusercontent.com/58770171/182595646-ebff1270-d38d-4d57-8cfe-22b29d70e87f.png)
But we can see, the semantics score did not caculate the reference answer from the previous question answer, since it did a refresh on the page, so the page will compare the current question's answer with the user input text. This caused the semantics score problem, I just tried to solve it, but have no ideas, wish someone can help me fix this problem.
![image](https://user-images.githubusercontent.com/58770171/182595749-71d14d5d-aac6-44fb-845e-fcf0048137b8.png)

**Comment by yanbo8204** [comment]
Could this issue result from this line https://github.com/linguisticsjusticeleague/PuzzLing-and-Scoring/blob/681e859766f3ea85d30efa7e9d80cd680ad0caa9/apps/home/routes.py#L70 

Because it seems that `index` is an undefined variable

**Comment by xiao11lam** [comment]
> Could this issue result from this line
> 
> https://github.com/linguisticsjusticeleague/PuzzLing-and-Scoring/blob/681e859766f3ea85d30efa7e9d80cd680ad0caa9/apps/home/routes.py#L70
> 
> Because it seems that `index` is an undefined variable

I dont think so, I think the main reason is that when we get into the result page, the input text is from the previous page. But when the backend get the input text, it will compare with the current "new" qustion from the ```pashto.txt``` file instead of the previous question from the last page.

**Comment by adiparashar** [comment]
I have fixed this issue please run the app from dashboard and verify
