### ISSUE TITLE
```home/routes.py``` The Database $PATH reference issue

### ISSUE THREAD

**Issue by xiao11lam** [linguisticsjusticeleague/PuzzLing-and-Scoring#5]
Hey, there! I tried to implement the score storage function at the ```dashboard``` branch, so each time the user can record their scores into their own database, and update continously when the user  tried new tests: https://github.com/linguisticsjusticeleague/PuzzLing-and-Scoring/tree/dashboard . It seemed the feature was done smoothly to me, and it works very fine now. 
Howerver, there was a small issue when I was developing, I found that the database cannot always be found just directly by the absolute path or other ways. I just tried some times, I was on Windows PC, I can only access the database by referring: ```C:\\Users\\ABC\\Desktop\\PuzzLing-and-Scoring\\apps\\db.sqlite3```. So it can be very unclear to me and also not good for the upcoming implementations, I hope if possible, guys can try this and run in your own machines to find out if there was any change of this section. 
![image](https://user-images.githubusercontent.com/58770171/189460354-dd5d819d-24cc-4e5e-86af-6e095be2890b.png)

**Comment by adiparashar** [comment]
fixed this issue please verify

**Comment by xiao11lam** [comment]
Thank you @aditya41295 , fixed perfectly!
